import Navbar from "../Navbar"

export const metadata = {
  title: 'Welcome',
  description: 'Generated by create next app',
}

export default function AuthLayout({ children }) {
    const tabs = [
        {
            name:   "Log in",
            link:   "login",
        },
        {
            name:   "Register",
            link:   "register",
        }
    ];

    return (
        <div className="min-w-[100vw] min-h-[100vh] bg-[--terminal-bg]">
            <div className="flex min-h-screen items-center py-[2.5vh] px-[2.5vh] md:pt-[20vh] text-[--terminal-primary] flex-col selection:bg-[--terminal-primary] selection:text-[--terminal-bg] glow-text">
                <div className="w-full md:w-[35rem]">
                    <div className="w-full">
                        <Navbar tabsData={tabs}></Navbar>
                    </div>
                    <div className="w-full border-2 border-[--terminal-primary] p-6 glow-box">
                        {children}
                    </div>
                </div>
            </div>
        </div>
    )
}